#!/usr/bin/env python3
import click
import os,sys,re
import subprocess
import time
from pathlib import Path

def add_rmd(File,To):
    To.write(f"\n```[r child=\"{File}\"]\n```\n".replace("[","{").replace("]","}"))

def check(Dir):
    if not Dir.is_dir():
        print(f"no such path {Dir}")
        sys.exit(1)

def clean(Dir):
    if not Dir.is_dir():
        os.mkdir(Dir)
    else:
        for the_file in os.listdir(Dir):
            file_path = os.path.join(Dir, the_file)
            try:
                if os.path.isfile(file_path):
                    os.unlink(file_path)
                #elif os.path.isdir(file_path): shutil.rmtree(file_path)
            except Exception as e:
                print(e)

def comp(file, compiles):
    if compiles:
        result = subprocess.Popen(['R', '-e', f"library(rmarkdown);render(\"{file}\")"],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        return result
    return None

def finish(compiles, cleanup, docdir):
    Docdir = Path(docdir)
    Srcdir = Docdir / "src"
    Pdfdir = Docdir / "pdf"
    Tmpdir = Docdir / "tmp"

    os.chdir(Srcdir)
    f = open(Srcdir / "main_master.rmd", "a")
    add_rmd("essay_master.rmd", f)
    f.close
    print("compiling main")
    p = comp("main.rmd", compiles)
    if not p is None:
        p.communicate()
    if cleanup:
        purge(Srcdir, "*.log")
        purge(Srcdir, "*_master.rmd")
    move(Srcdir, "main.pdf", Pdfdir)
    move(Tmpdir, "*.pdf", Pdfdir)
    move(Tmpdir, "*.log", Pdfdir)
    if cleanup:
        purge(Tmpdir, "*")
        os.rmdir(Tmpdir)

def indexadd(File, idx):
    File.write(f"\n\\index[{idx}]\n".replace("[", "{").replace("]", "}"))

def move(dir, pattern, to):
    for f in Path(dir).glob(pattern):
        os.rename(str(f), str(f).replace(str(dir), str(to)))

def purge(dir, pattern):
    for p in Path(dir).glob(pattern):
        p.unlink()

@click.group()
def main():
    """Document Manager"""

@main.command()
@click.option('--docdir', '-d', default=str(Path.home() / "Documents"),
        help="Directory of the documents (default=$home/Documents)")
@click.option('--cfgdir', '-c', default=str(Path.home() / "Documents" / "inf"),
        help="Directory of the configuration files (default=$home/Documents/inf)")
@click.argument('name')
@click.argument('section')
@click.argument('index', nargs=-1)
@click.option('--docdir', '-d', default=str(Path.home() / "Documents"),
        help="Directory of the documents (default=$home/Documents)")
@click.option('--cfgdir', '-c', default=str(Path.home() / "Documents" / "inf"),
        help="Directory of the configuration files (default=$home/Documents/inf)")
def add(name, section, index, docdir, cfgdir):
    """Creates a document and adds it to index"""
    Docdir  = Path(docdir)
    Cfgdir  = Path(cfgdir)
    Srcdir  = Docdir / "src"

    filename = f"{section}_{name}.doc"
    open(f"{str(Srcdir)}/{filename}", 'w+').close()
    indexstr = ",".join(index)
    with open(str(Cfgdir / "index.csv"), 'a') as idx:
        idx.write(f"{filename},{indexstr}")

@main.command()
def list():
    """Lists the documents"""

@main.command()
@click.option('--docdir', '-d', default=str(Path.home() / "Documents"),
        help="Directory of the documents (default=$home/Documents)")
@click.option('--cfgdir', '-c', default=str(Path.home() / "Documents" / "inf"),
        help="Directory of the configuration files (default=$home/Documents/inf)")
@click.option('--nocompile',    default=False, is_flag=True,
        help="dont compile the documents")
@click.option('--nocleanup',    default=False, is_flag=True,
        help="dont cleanup after compiling")
@click.option('--proccount',    default=0,
        help="maximum documents to compile at once")
@click.option('--index', '-i' , default=False, is_flag=True,
        help="prints the index and exits")
def compile(nocompile, nocleanup, proccount, docdir, cfgdir, index):
    """Compiles docments using RMarkdown."""
    compiles = not nocompile
    cleanup = not nocleanup

    Docdir  = Path(docdir)
    Cfgdir  = Path(cfgdir)
    Srcdir  = Docdir / "src"
    Pdfdir  = Docdir / "pdf"
    Tmpdir  = Docdir / "tmp"

    check(Docdir)
    check(Srcdir)
    check(Cfgdir)
    check(Pdfdir)
    clean(Tmpdir)
    purge(Srcdir, "*_master.rmd")

    with open(f"{Srcdir}/essay_master.rmd", "w") as em:
        em.write("\\phantomsection\n\\addcontentsline{toc}{section}{Esseys}")
    mm = open(Srcdir / "main_master.rmd", "w+")

    with open(Cfgdir / "sections", "r") as file:
        sections = file.read()[:-1].split("\n")

    with open(Cfgdir / "index.csv", "r") as file:
        read = file.read()[:-1].split("\n")
        index = {}
        for i in read:
            data = i.split(",")
            index[data[0]] = data[1:]

    os.chdir(Tmpdir)
    queue = []
    for section in sorted(sections):
        print(f"started compiling {section}")
        sm = open(f"{Srcdir}/{section}_master.rmd", "w+")
        sm.write(f"\\newpage\n\n# {section}")
        add_rmd(f"{section}_master.rmd", mm)
        for file in sorted(Path(Srcdir).glob(f"{section}_*")):
            if file != Path(f"{Srcdir}/{section}_master.rmd"):
                if "doc" == file.name.split(".")[-1]:
                    subsecname = file.name.replace("The", "")\
                            .replace(f"{section}_", "")\
                            .replace(f".doc", "")\
                            .replace(f"_", " ")
                    sm.write(f"\n## {subsecname}")
                    try:
                        for i in index[file.name]:
                            indexadd(sm, i)
                    except:
                        print(f"add {file.name} to index.csv")
                    add_rmd(file.name, sm)
                    newfile=file.name.replace("doc", "rmd")
                    with open(f"{Tmpdir}/{newfile}", "w+") as tmpfile:
                        with open(f"{Cfgdir}/doc_header", "r") as header:
                            for line in header:
                                addline = line.replace("<Title>", subsecname)
                                tmpfile.write(addline)
                        with open(file, "r") as srcfile:
                            for line in srcfile:
                                lineadd = line
                                tmpfile.write(lineadd)
                    p = comp(newfile, compiles)
                    if not p is None:
                        queue.append(p)
                    if proccount != 0:
                        if proccount <= len(queue):
                            queue[-1].communicate()
                            del queue[-1]
                elif "ess" == file.name.split(".")[-1]:
                    newfile=file.name.replace("ess", "rmd")
                    filetitle = file.name.replace("The", "")\
                            .replace(f"{section}_", "")\
                            .replace(f".doc", "")\
                            .replace(f"_", " ")
                    with open(f"{Tmpdir}/{newfile}", "w+") as tmpfile:
                        with open(f"{Srcdir}/essay_master.rmd", "a") as em:
                            em.write(f"\n\\includepdf[pages=-]({file})\n".replace("(","{").replace(")","}"))
                        with open(f"{Cfgdir}/essay_header", "r") as header:
                            for line in header:
                                addline = line.replace("<Title>", subsecname)
                                tmpfile.write(addline)
                        with open(file, "r") as srcfile:
                            for line in srcfile:
                                lineadd = line
                                tmpfile.write(lineadd)
                    p = comp(newfile, compiles)
                    if not p is None:
                        queue.append(p)
                    if proccount != 0:
                        if proccount <= len(queue):
                            queue[-1].communicate()
                            del queue[-1]
                else:
                    print(f"bad file type {file}")
        sm.close()
    for i in queue:
        i.communicate()
    mm.close()
    finish(compiles, cleanup, docdir)

if __name__ == "__main__":
    main()
