language: python
python:
  - "3.6"
  - "3.6-dev"
# command to install dependencies
install:
  - pip3 install setuptools
  - python3 setup.py install
# command to run tests
script:
  - autormd setup
  - autormd add lol nope
  - autormd compile --linux
