---
numbersections: true
output:
    pdf_document:
      highlight: pygments
header-includes:
  - \usepackage{times}
  - \usepackage[margin=1in]{geometry}
  - \usepackage{tocloft}
  - \usepackage{times}
  - \usepackage{indentfirst}
  - \usepackage[numbers]{natbib}
  - \usepackage{tabularx}
  - \usepackage[dvipsnames]{xcolor}
  - \usepackage{graphicx}
  - \usepackage{booktabs}
  - \usepackage{mwe}
  - \usepackage{imakeidx}
  - \usepackage{scrlayer-scrpage}
  - \usepackage{hanging}
  - \usepackage{hyperref}
  - \usepackage{tabto}
  - \usepackage[final]{pdfpages}
  - \makeindex[columns=2]
  - \newcolumntype{Y}{>{\centering\arraybackslash}X}
  - \pagestyle{scrheadings}
  - \renewcommand{\cftsecfont}{\large\noindent\break\rule{.4\textwidth}{1pt}\tabto*{0cm}}
  - \setlength{\columnsep}{2cm}
  - \renewcommand{\cftsubsubsecfont}{\footnotesize}
  - \clearpairofpagestyles
  - \ohead{\rightmark}
  - \cfoot[\pagemark]{\pagemark}
  - \setcounter{tocdepth}{3}
  - \setlength{\columnseprule}{1pt}
fontsize: 12pt
---
\begin{titlepage}
  \begin{center}
  \hfill
  \parbox{\linewidth}{
    \centering
    Newark High School\par
  }
  \hfill
  \par
    \vspace{.05\textheight}
    {\LARGE\scshape NOTES\par}
    \vspace{.05\textheight}
    \par
    {\itshape\large Every doc on my computer \par}
    \vspace{.05\textheight}
    By \textsc{Preston Precourt}\par
    \vspace{.05\textheight}
    \begin{tabularx}{\textwidth}{Y}
      \toprule
      {\Huge\bfseries Notes 2018--2019 \par} \\
      \bottomrule
    \end{tabularx}
    \vspace{.05\textheight}
    {\large \par}
    \vfill
    \noindent\begin{tabularx}{\textwidth}{XXXX}
      \toprule
      Name & Grade & School & Class \\
      \midrule
      Preston & 10 & Newark & Ela\\
      Preston & 10 & Newark & Social Studies\\
  \bottomrule
  \end{tabularx}
\end{center}
\end{titlepage}

\begin{multicols}{2}

\tableofcontents

\end{multicols}

```{r child='main_master.rmd'}

```

\clearpage
\phantomsection
\addcontentsline{toc}{section}{Index}
\printindex
\clearpage
\phantomsection
\addcontentsline{toc}{section}{refrences}
\bibliographystyle{plain}
\bibliography{/home/john/Documents/cit/uni}
